name: corona_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  bloc: ^3.0.0
  cupertino_icons: ^0.1.3
  charts_flutter: ^0.9.0
  device_preview: ^0.3.0+1
  dio: ^3.0.9
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  flutter_localized_locales: ^1.1.0
  fluttertoast: ^4.0.1
  flutter_screenutil: ^1.1.0
  flutter_offline: ^0.3.0
  get_it: ^4.0.1
  google_maps_flutter: ^0.5.25+2
  intl: ^0.16.0
  logger: ^0.8.3
  page_transition: ^1.1.5
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  sliding_up_panel: ^1.0.0
  shimmer: ^1.1.0

dev_dependencies:
  bloc_test: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
